name: Slipdisk
main: com.spinalcraft.slipdisk.Slipdisk
version: 1.0

depend: [Spinalpack]

commands:
  slipdisk:
    description: Learn about Slipdisk
    usage: Usage - /slipdisk
    aliases: slip
    
  deleteslip:
    description: Delete a user's slip entirely
    usage: Usage - /deleteslip <username>
    permission: slipdisk.deleteslip
    permission-message: No!
  
  elevate:
    description: Elevate a user's privileges in Slipdisk
    usage: Usage - /elevate <username> <level>
    permission: slipdisk.elevate
    permission-message: No!
  
  debug:
    description: Display exceptions
    usage: Usage - /debug [on | off]
    permission: slipdisk.debug
    permission-message: No!